DO $$ BEGIN

	CREATE SCHEMA IF NOT EXISTS "info";

	CREATE TABLE IF NOT EXISTS info."Clients"
	(
		"Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
		"Created" timestamp(6) with time zone,
		"Updated" timestamp(6) with time zone,
		"Deleted" timestamp(6) with time zone,
		"UniId" uuid NOT NULL,
		"FirstName" varchar(255) NOT NULL,
		"MiddleName" varchar(255) NOT NULL,
		"LastName" varchar(255) NOT NULL,
		"Balance" decimal NOT NULL,
		CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
	);

END $$;