DO $$ BEGIN

	CREATE SCHEMA IF NOT EXISTS "info";

	CREATE TABLE IF NOT EXISTS info."Transactions"
	(
		"Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
		"Created" timestamp(6) with time zone,
		"Updated" timestamp(6) with time zone,
		"Deleted" timestamp(6) with time zone,
		"UniId" uuid NOT NULL,
		"TransactionType" smallint NOT NULL,
		"Amount" decimal NOT NULL,
		"ClientId" uuid NOT NULL,
		"TransactionDateTime" timestamp(6) with time zone NOT NULL,
		CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id")
	);

END $$;